### ISSUE TITLE
Issues from original meta PR

### ISSUE THREAD

**Issue by talex5** [ocurrent/opam-repo-ci#49]
Moved from https://github.com/ocurrent/ocaml-ci/pull/192. List probably needs updating and/or splitting into separate issues.

* [ ] Create an archive cache service / Remove buildkit
* [ ] Add a way to get the revdeps in the solver (opam-ci currently uses `opam list`)
* [ ] Make the client API return a tree-like structure for statuses. This allows easier `citty` support. (opam-ci currently reconstructs the tree in the web-ui service, see https://github.com/ocurrent/ocaml-ci/pull/155)
* [X] Check the merge commit for PRs instead of the branch HEAD (opam-ci currently merges by hand in each `docker build`)
* [ ] Dealing with failed states better (see https://github.com/ocurrent/ocurrent/issues/181)
